---
- hosts: all
  become: yes
  gather_facts: yes

  roles:
    - geerlingguy.nfs
    - geerlingguy.packer-debian
    - geerlingguy.git
    - geerlingguy.docker
    - gantsign.intellij
    - gantsign.java
    - gantsign.maven
  
  tasks:
    - apt:
        name:
        - wget
        - curl
        - vim
        - htop
        - tmux
